# Generated by Django 4.2.11 on 2024-05-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(null=True, upload_to="producto"),
        ),
    ]
