# Generated by Django 4.2.11 on 2024-05-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_producto_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("rut", models.CharField(max_length=10)),
                (
                    "motivo",
                    models.IntegerField(
                        choices=[[0, "reclamo"], [1, "sugerencia"], [2, "ayuda"]]
                    ),
                ),
                ("mensaje", models.TextField()),
            ],
        ),
    ]
