# Generated by Django 4.2.11 on 2024-05-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_contacto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=100)),
                ("producto", models.CharField(max_length=100)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estado", models.CharField(max_length=50)),
            ],
        ),
    ]
