# Generated by Django 4.2.11 on 2024-05-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_cart_cartitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boleta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_boleta", models.CharField(max_length=50)),
                ("cliente", models.CharField(max_length=100)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField()),
            ],
        ),
    ]
