# Generated by Django 4.2.11 on 2024-05-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_boleta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boleta",
            name="id",
        ),
        migrations.AlterField(
            model_name="boleta",
            name="id_boleta",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
