# Generated by Django 4.2.11 on 2024-05-27 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_customusuarios_trabajadores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trabajadores",
            name="CustomUsuarios",
        ),
        migrations.DeleteModel(
            name="CustomUsuarios",
        ),
        migrations.DeleteModel(
            name="trabajadores",
        ),
    ]
