# Generated by Django 4.2.11 on 2024-05-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_remove_trabajadores_customusuarios_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="quantity",
            new_name="cantidad",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="created_at",
        ),
        migrations.AddField(
            model_name="cart",
            name="estado",
            field=models.CharField(
                choices=[("pendiente", "Pendiente"), ("pagado", "Pagado")],
                default="pendiente",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
