# Generated by Django 4.2.11 on 2024-05-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_rename_quantity_cartitem_cantidad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boleta",
            name="id_boleta",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
